export const companies = [
  
  { label: '3forge' },
  { label: '99.co' },
  { label: 'Agency for Science, Technology and Research (A*STAR)' },
  { label: 'Advanced Micro Devices (AMD)' },
  { label: 'Advantir Innovations' },
  { label: 'Accenture' },
  { label: 'Accuracy' },
  { label: 'Acronis' },
  { label: 'Agoda' },
  { label: 'AlphaLab Capital' },
  { label: 'Alstom' },
  { label: 'Amaris AI' },
  { label: 'Amazon' },
  { label: 'Ant Group' },
  { label: 'Apple' },
  { label: 'Ascenda' },
  { label: 'Atome' },
  { label: 'Autodesk' },
  { label: 'Avanade' },
  { label: 'Bank of America' },
  { label: 'Bank of Singapore' },
  { label: 'betterdata.ai' },
  { label: 'Binance' },
  { label: 'Bosch' },
  { label: 'ByteDance' },
  { label: 'Centre for Strategic Infocomm Technologies (CSIT)' },
  { label: 'Carro' },
  { label: 'Chemistry Consultancy' },
  { label: 'Chilli Api' },
  { label: 'Circles.Life' },
  { label: 'Cisco' },
  { label: 'Citibank' },
  { label: 'Cloudflare' },
  { label: 'ComfortDelGro' },
  { label: 'Conservation International' },
  { label: 'Constructor' },
  { label: 'Continental' },
  { label: 'Creative' },
  { label: 'Credit Suisse' },
  { label: 'Crypto.com' },
  { label: 'Design Insight' },
  { label: 'Development Bank of Singapore (DBS)' },
  { label: 'Dalsey, Hillblom and Lynn (DHL)' },
  { label: 'DRW' },
  { label: 'DSO National Laboratories' },
  { label: 'Defence Science and Technology Agency (DSTA)' },
  { label: 'Daiwa Capital Markets' },
  { label: 'Dell' },
  { label: 'Dyson' },
  { label: 'Energy Market Authority (EMA)' },
  { label: 'Equinix' },
  { label: 'Ernst & Young (EY)' },
  { label: 'ExpressVPN' },
  { label: 'F5 Networks' },
  { label: 'Facebook' },
  { label: 'Fjord' },
  { label: 'foodpanda' },
  { label: 'Government of Singapore Investment Corporation (GIC)' },
  { label: 'GlobalFoundries' },
  { label: 'Goldman Sachs' },
  { label: 'Google' },
  { label: 'GovTech' },
  { label: 'Grab' },
  { label: 'Grasshopper' },
  { label: 'Housing & Development Board (HDB)' },
  { label: 'HOPE Technik' },
  { label: 'HTX' },
  { label: 'Hodlnaut' },
  { label: 'HOL Experiences' },
  { label: 'Hypotenuse AI' },
  { label: 'International Business Machines (IBM)' },
  { label: 'Ideactio' },
  { label: 'IDEMIA' },
  { label: 'Integrated Health Information Systems (IHiS)' },
  { label: 'Infocomm Media Development Authority (IMDA)' },
  { label: 'Illumina' },
  { label: 'Indeed' },
  { label: 'Infineon' },
  { label: 'Institute for Infocomm Research (I2R)' },
  { label: 'JPMorgan Chase' },
  { label: 'Jane Street' },
  { label: 'Johnson & Johnson' },
  { label: 'Jump Trading' },
  { label: 'KPMG' },
  { label: 'Lionsbot' },
  { label: 'Monetary Authority of Singapore (MAS)' },
  { label: 'MindFi' },
  { label: 'Ministry of Education (MOE)' },
  { label: 'Ministry of Finance (MOF)' },
  { label: 'Mandiant' },
  { label: 'Meta' },
  { label: 'Micron Technology' },
  { label: 'Millennium Management' },
  { label: 'Morgan Stanley' },
  { label: 'Motional' },
  { label: 'National Computer Systems (NCS)' },
  { label: 'National University of Singapore (NUS)' },
  { label: 'NextOfKin Creatives' },
  { label: 'NTUC Income' },
  { label: 'Ninja Van' },
  { label: 'OLIVIA LEE' },
  { label: 'Oversea-Chinese Banking Corp (OCBC)' },
  { label: 'Open Government Products (OGP)' },
  { label: 'Philips' },
  { label: 'Plus65 Interactive' },
  { label: 'Pushlytics' },
  { label: 'Port of Singapore Authority (PSA)' },
  { label: 'Panasonic' },
  { label: 'PayPal' },
  { label: 'Procter & Gamble' },
  { label: 'PricewaterhouseCoopers (PwC)' },
  { label: 'Quantedge' },
  { label: 'RBS Design' },
  { label: 'Rakuten' },
  { label: 'Ramco Systems' },
  { label: 'Razer' },
  { label: 'REC Solar' },
  { label: 'ST Engineering' },
  { label: 'STUCK Design' },
  { label: 'Singapore Airlines' },
  { label: 'Singapore Tourism Board (STB)' },
  { label: 'Studio Juju' },
  { label: 'Superstructure' },
  { label: 'Singapore Armed Forces (SAF)' },
  { label: 'SAP' },
  { label: 'SGInnovate Infinity Series' },
  { label: 'SGInnovate Summation Series' },
  { label: 'Singapore Institute of Technology (SIT)' },
  { label: 'Schneider Electric' },
  { label: 'Sea' },
  { label: 'Seagate Technology' },
  { label: 'SenseTime' },
  { label: 'ShopBack' },
  { label: 'Shopee' },
  { label: 'Siemens' },
  { label: 'Singtel' },
  { label: 'Skyline Communications' },
  { label: 'Sprinklr' },
  { label: 'Squarepoint Capital' },
  { label: 'Standard Chartered' },
  { label: 'StashAway' },
  { label: 'Stealth Startup' },
  { label: 'Stripe' },
  { label: 'TTI Electronics' },
  { label: 'Tesla' },
  { label: 'Thales' },
  { label: 'Thoughtworks' },
  { label: 'TikTok' },
  { label: 'Titansoft' },
  { label: 'Trail of Bits' },
  { label: 'UCARS' },
  { label: 'Ubisoft Singapore' },
  { label: 'Venture Corporation' },
  { label: 'Viki' },
  { label: 'Virtu Financial' },
  { label: 'Visa' },
  { label: 'Vividthree Productions' },
  { label: 'Wintermute' },
  { label: 'Wise' },
  { label: 'Workato' },
  { label: 'Workclass' },
  { label: 'Yara' },
  { label: 'Zendesk' },
];

export const companyList = [
  '3forge',
  '99.co',
  'Accenture',
  'Accuracy',
  'Acronis',
  'Advanced Micro Devices (AMD)',
  'Agency for Science, Technology and Research (A*STAR)',
  'Agoda',
  'AlphaLab Capital',
  'Alstom',
  'Amaris AI',
  'Amazon',
  'Ant Group',
  'Apple',
  'Ascenda',
  'Atome',
  'Autodesk',
  'Avanade',
  'Bank of America',
  'Bank of Singapore',
  'Binance',
  'Bosch',
  'ByteDance',
  'Carousell',
  'Carro',
  'Centre for Strategic Infocomm Technologies (CSIT)',
  'Chilli Api',
  'Circles.Life',
  'Cisco',
  'Citibank',
  'Cloudflare',
  'ComfortDelGro',
  'Conservation International',
  'Constructor',
  'Continental',
  'Creative',
  'Credit Suisse',
  'Crypto.com',
  'DRW',
  'DSO National Laboratories',
  'Daiwa Capital Markets',
  'Dalsey, Hillblom and Lynn (DHL)',
  'Defence Science and Technology Agency (DSTA)',
  'Dell',
  'Development Bank of Singapore (DBS)',
  'Dyson',
  'Energy Market Authority (EMA)',
  'Equinix',
  'Ernst & Young (EY)',
  'ExpressVPN',
  'F5 Networks',
  'Facebook',
  'Garena',
  'GlobalFoundries',
  'Goldman Sachs',
  'Google',
  'GovTech',
  'Government of Singapore Investment Corporation (GIC)',
  'Grab',
  'Grasshopper',
  'HOPE Technik',
  'HTX',
  'Hodlnaut',
  'Housing & Development Board (HDB)',
  'Hypotenuse AI',
  'IDEMIA',
  'Illumina',
  'Indeed',
  'Infineon',
  'Infocomm Media Development Authority (IMDA)',
  'Institute for Infocomm Research (I2R)',
  'Integrated Health Information Systems (IHiS)',
  'International Business Machines (IBM)',
  'JPMorgan Chase',
  'Jane Street',
  'Johnson & Johnson',
  'Jump Trading',
  'KPMG',
  'Lazada',
  'Mandiant',
  'Meta',
  'Micron Technology',
  'Millennium Management',
  'Ministry of Education (MOE)',
  'Ministry of Finance (MOF)',
  'Monetary Authority of Singapore (MAS)',
  'Morgan Stanley',
  'Motional',
  'NTUC Income',
  'National Computer Systems (NCS)',
  'Ninja Van',
  'Open Government Products (OGP)',
  'Oversea-Chinese Banking Corp (OCBC)',
  'Panasonic',
  'PayPal',
  'Peicai Secondary School',
  'Port of Singapore Authority (PSA)',
  'PricewaterhouseCoopers (PwC)',
  'Procter & Gamble',
  'Quantedge',
  'Rakuten',
  'Ramco Systems',
  'Razer',
  'Rec',
  'SAP',
  'SGInnovate Infinity Series',
  'SGInnovate Summation Series',
  'ST Engineering',
  'Schneider Electric',
  'Sea',
  'Seagate Technology',
  'SenseTime',
  'ShopBack',
  'Shopee',
  'Siemens',
  'Singapore Armed Forces (SAF)',
  'Singapore Institute of Technology (SIT)',
  'Singtel',
  'Skyline Communications',
  'Sprinklr',
  'Squarepoint Capital',
  'Standard Chartered',
  'StashAway',
  'Stealth Startup',
  'Stripe',
  'Syngenta',
  'Tesla',
  'Thales',
  'Thoughtworks',
  'TikTok',
  'Titansoft',
  'Trail of Bits',
  'UCARS',
  'UOB',
  'Ubisoft Singapore',
  'Venture Corporation',
  'Viki',
  'Virtu Financial',
  'Visa',
  'Wintermute',
  'Wise',
  'Workato',
  'Workclass',
  'Yara',
  'Zendesk',
  'betterdata.ai',
  'company',
  'foodpanda',
  'Singapore Tourism Board (STB)',
  'Chemistry Consultancy',
  'National University of Singapore (NUS)',
  'HOL Experiences',
  'Plus65 Interactive',
  'Lionsbot',
  'STUCK Design',
  'Studio Juju',
  'MindFi',
  'Ideactio',
  'Singapore Airlines',
  'Advantir Innovations',
  'Fjord',
  'ST Engineering',
  'OLIVIA LEE',
  'NextOfKin Creatives',
  'Design Insight',
  'Vividthree Productions',
  'Superstructure',
  'RBS Design',
  'TTI, Inc.',
  'Philips',
  'Pushlytics',
]