export const jobsCategory = [
  
    { label: 'Software Engineer', category: 'Software' },
    { label: 'Frontend Engineer', category: 'Software' },
    { label: 'Backend Engineer', category: 'Software' },
    { label: 'Fullstack Engineer', category: 'Software' },
    { label: 'Web Developer', category: 'Software' },
    { label: 'Mobile Developer', category: 'Software' },
    { label: 'DevOps Engineer', category: 'Software' },
    { label: 'Quality Assurance Engineer', category: 'Software' },
    { label: 'Security Engineer', category: 'Software' },
  
  // { label: 'Product Manager', category: 'Product' },
  // { label: 'Project Manager', category: 'Product' },
  // { label: 'Product Operations', category: 'Product' },
  // { label: 'Product Designer', category: 'Product' },
  // { label: 'UI/UX Designer', category: 'Product' },

  // { label: 'QA Engineer', category: 'Software' },
  // { label: 'Scrum Master', category: 'Software' },
  // { label: 'Software Architect', category: 'Software' },
  // { label: 'Software Engineer', category: 'Software' },
  // { label: 'Software Manager', category: 'Software' },

  // { label: 'Data Analyst', category: 'Data' },
  // { label: 'Data Architect', category: 'Data' },
  // { label: 'Data Scientist', category: 'Data' },
  // { label: 'Database Administrator', category: 'Data' },
  // { label: 'Machine Learning Engineer', category: 'Data' },
  // { label: 'Statistician', category: 'Data' },
  // { label: 'Systems Analyst', category: 'Data' },

  // { label: 'Accountant', category: 'Business' },
  // { label: 'Administration', category: 'Business' },
  // { label: 'Business Analyst', category: 'Business' },
  // { label: 'Business Development', category: 'Business' },
  // { label: 'Customer Service', category: 'Business' },
  // { label: 'Finance', category: 'Business' },
  // { label: 'Human Resources', category: 'Business' },
  // { label: 'Marketing', category: 'Business' },
  // { label: 'Operations', category: 'Business' },
  // { label: 'Sales', category: 'Business' },

  // { label: 'Business Consultant', category: 'Consulting' },
  // { label: 'Consultant', category: 'Consulting' },
  // { label: 'Financial Consultant', category: 'Consulting' },
  // { label: 'HR Consultant', category: 'Consulting' },
  // { label: 'Sales Consultant', category: 'Consulting' },
  // { label: 'Technology Consultant', category: 'Consulting' },
  // { label: 'Marketing Consultant', category: 'Consulting' },

  // { label: 'Aerospace Engineer', category: 'Engineering' },
  // { label: 'Biomedical Engineer', category: 'Engineering' },
  // { label: 'Chemical Engineer', category: 'Engineering' },
  // { label: 'Civil Engineer', category: 'Engineering' },
  // { label: 'Computer Engineer', category: 'Engineering' },
  // { label: 'Construction Engineer', category: 'Engineering' },
  // { label: 'Electrical Engineer', category: 'Engineering' },
  // { label: 'Electronic Engineer', category: 'Engineering' },
  // { label: 'Environmental Engineer', category: 'Engineering' },
  // { label: 'Industrial Engineer', category: 'Engineering' },
  // { label: 'Manufacturing Engineer', category: 'Engineering' },
  // { label: 'Marine Engineer', category: 'Engineering' },
  // { label: 'Materials Engineer', category: 'Engineering' },
  // { label: 'Mechanical Engineer', category: 'Engineering' },
  // { label: 'Nuclear Engineer', category: 'Engineering' },
  // { label: 'Petroleum Engineer', category: 'Engineering' },
  // { label: 'Process Engineer', category: 'Engineering' },
  // { label: 'Quality Engineer', category: 'Engineering' },
  // { label: 'Structural Engineer', category: 'Engineering' },
  // { label: 'Systems Engineer', category: 'Engineering' },
  // { label: 'Thermal Engineer', category: 'Engineering' },

  // { label: 'Architect', category: 'Arts & Entertainment' },
  // { label: 'Artist', category: 'Arts & Entertainment' },
  // { label: 'Athlete', category: 'Arts & Entertainment' },
  // { label: 'Comedian', category: 'Arts & Entertainment' },
  // { label: 'Culinary Arts', category: 'Arts & Entertainment' },
  // { label: 'Curator', category: 'Arts & Entertainment' },
  // { label: 'Dance', category: 'Arts & Entertainment' },
  // { label: 'Designer', category: 'Arts & Entertainment' },
  // { label: 'Entertainer', category: 'Arts & Entertainment' },
  // { label: 'Event Planner', category: 'Arts & Entertainment' },
  // { label: 'Hairstylist', category: 'Arts & Entertainment' },
  // { label: 'Illustrator', category: 'Arts & Entertainment' },
  // { label: 'Photographer', category: 'Arts & Entertainment' },
  // { label: 'Sculptor', category: 'Arts & Entertainment' },
  // { label: 'Singer', category: 'Arts & Entertainment' },
  // { label: 'Teacher', category: 'Arts & Entertainment' },
  // { label: 'Writer', category: 'Arts & Entertainment' },

];

export const jobsListTechnology = [
  'Software Engineer',
  'Frontend Engineer',
  'Backend Engineer',
  'Fullstack Engineer',
  'Web Developer',
  'Mobile Developer',
  'DevOps Engineer',
  'Quality Assurance Engineer',
  'Security Engineer',
]

export const jobsList = [
  // 'Accountant',
  // 'Administration',
  // 'Aerospace Engineer',
  // 'Architect',
  // 'Artist',
  // 'Athlete',
  // 'Biomedical Engineer',
  // 'Business Analyst',
  // 'Business Consultant',
  // 'Business Development',
  // 'Chemical Engineer ',
  // 'Civil Engineer',
  // 'Comedian',
  // 'Computer Engineer',
  // 'Construction Engineer',
  // 'Consultant',
  // 'Culinary Arts',
  // 'Curator',
  // 'Customer Service',
  // 'Dance',
  // 'Data Analyst',
  // 'Data Architect',
  // 'Data Scientist',
  // 'Database Administrator',
  // 'Designer',
  // 'Electrical Engineer',
  // 'Electronic Engineer',
  // 'Entertainer',
  // 'Environmental Engineer',
  // 'Event Planner',
  // 'Finance',
  // 'Financial Consultant',
  // 'HR Consultant',
  // 'Hairstylist',
  // 'Human Resources',
  // 'Illustrator',
  // 'Industrial Engineer',
  // 'Machine Learning Engineer',
  // 'Manufacturing Engineer',
  // 'Marine Engineer',
  // 'Marketing',
  // 'Marketing Consultant',
  // 'Materials Engineer',
  // 'Mechanical Engineer',
  // 'Nuclear Engineer',
  // 'Operations',
  // 'Petroleum Engineer',
  // 'Photographer',
  // 'Process Engineer',
  // 'Product Designer',
  // 'Product Manager',
  // 'Product Operations',
  // 'Project Manager',
  // 'QA Engineer',
  // 'Quality Engineer',
  // 'Sales',
  // 'Sales Consultant',
  // 'Scrum Master',
  // 'Sculptor',
  // 'Singer',
  // 'Software Architect',
  // 'Software Engineer',
  // 'Software Manager',
  // 'Statistician',
  // 'Structural Engineer',
  // 'Systems Analyst',
  // 'Systems Engineer',
  // 'Teacher',
  // 'Technology Consultant',
  // 'Thermal Engineer',
  // 'UI/UX Designer',
  // 'Writer',  
]