// Mapping for companies whose names are not:
// 1) Abc (Single words and Capitalised)
// 2) Abc Bce (Multiple words and Capitalised)
// or if you want to add the abbreviation in

export const CompanyNameToURL = {
  'Agency for Science, Technology and Research (A*STAR)': 'agency-for-science-technology-and-research-A-STAR',
  'Advanced Micro Devices (AMD)': 'advanced-micro-devices-amd',
  'AlphaLab Capital': 'alphalab-capital',
  'Amaris AI': 'amaris-ai',
  'Bank of America': 'bank-of-america-boa',
  'Bank of Singapore': 'bank-of-singapore-bos',
  'betterdata.ai': 'betterdata-ai',
  'ByteDance': 'bytedance',
  'Centre for Strategic Infocomm Technologies (CSIT)': 'center-for-strategic-infocomm-technologies-csit',
  'Circles.Life': 'circles-life',
  'Crypto.com': 'crypto-com',
  'Development Bank of Singapore (DBS)': 'development-bank-of-singapore-dbs',
  'Dalsey, Hillblom and Lynn (DHL)': 'dalsey-hillblom-and-lynn-dhl',
  'Defence Science and Technology Agency (DSTA)': 'defence-science-and-technology-agency-dsta',
  'Energy Market Authority (EMA)': 'energy-market-authority-ema',
  'Ernst & Young (EY)': 'ernst-&-young-ey',
  'ExpressVPN': 'expressvpn',
  'F5 Networks': 'f5-networks',
  'foodpanda': 'foodpanda',
  'Government of Singapore Investment Corporation (GIC)': 'government-of-singapore-investment-corporation-gic',
  'GlobalFoundries': 'globalfoundries',
  'GovTech': 'govtech',
  'HOL Experiences': 'hol-experiences',
  'Housing & Development Board (HDB)': 'housing-and-development-board-hdb',
  'HOPE Technik': 'hope-technik',
  'Hypotenuse AI': 'hypotenuse-ai',
  'International Business Machines (IBM)': 'international-business-machines-ibm',
  'IDEMIA': 'idemia',
  'Integrated Health Information Systems (IHiS)': 'integrated-health-information-systems-ihis',
  'Infocomm Media Development Authority (IMDA)': 'infocomm-media-development-authority-imda',
  'Institute for Infocomm Research (I2R)': 'institute-for-infocomm-research-i2r',
  'JPMorgan Chase': 'jpmorgan-chase',
  'Johnson & Johnson': 'johnson-&-johnson',
  'KPMG': 'kpmg',
  'MindFi': 'mindfi',
  'Monetary Authority of Singapore (MAS)': 'monetary-authority-of-singapore-mas',
  'Ministry of Education (MOE)': 'ministry-of-education-moe',
  'Ministry of Finance (MOF)': 'ministry-of-finance-mof',
  'National University of Singapore (NUS)': 'national-university-of-singapore-nus',
  'NextOfKin Creatives': 'nextofkin-creatives',
  'National Computer Systems (NCS)': 'national-computer-systems-ncs',
  'NTUC Income': 'ntuc-income',
  'OLIVIA LEE': 'olivia-lee',
  'Oversea-Chinese Banking Corp (OCBC)': 'oversea-chinese-banking-corp-ocbc',
  'Open Government Products (OGP)': 'open-government-products-ogp',
  'Port of Singapore Authority (PSA)': 'port-of-singapore-authority-psa',
  'PayPal': 'paypal',
  'Procter & Gamble': 'proctor-&-gamble',
  'PricewaterhouseCoopers (PwC)': 'pricewaterhousecoopers-pwc',
  'REC Solar': 'rec-solar',
  'RBS Design': 'rbs-design',
  'ST Engineering': 'st-engineering',
  'STUCK Design': 'stuck-design',
  'Singapore Tourism Board (STB)': 'singapore-tourism-board-stb',
  'Singapore Armed Forces (SAF)': 'singapore-armed-forces-saf',
  'SAP': 'sap',
  'SGInnovate Infinity Series': 'sginnovate-infinity-series',
  'SGInnovate Summation Series': 'sginnovate-summation-series',
  'Singapore Institute of Technology (SIT)': 'singapore-institute-of-technology-sit',
  'SenseTime': 'sensetime',
  'ShopBack': 'shopback',
  'StashAway': 'stashaway',
  'TTI, Inc.': 'tti-inc',
  'TikTok': 'tiktok',
  'Trail of Bits': 'trail-of-bits',
  'UCARS': 'ucars',
}

export const CompanyURLToName = {
  '99-co': '99.co',
  'agency-for-science-technology-and-research-A-STAR': 'Agency for Science, Technology and Research (A*STAR)',
  'advanced-micro-devices-amd': 'Advanced Micro Devices (AMD)',
  'alphalab-capital': 'AlphaLab Capital',
  'amaris-ai': 'Amaris AI',
  'bank-of-america-boa': 'Bank of America',
  'bank-of-singapore-bos': 'Bank of Singapore',
  'betterdata-ai': 'betterdata.ai',
  'bytedance': 'ByteDance',
  'center-for-strategic-infocomm-technologies-csit': 'Centre for Strategic Infocomm Technologies (CSIT)',
  'circles-life': 'Circles.Life',
  'crypto-com': 'Crypto.com',
  'development-bank-of-singapore-dbs': 'Development Bank of Singapore (DBS)',
  'dalsey-hillblom-and-lynn-dhl': 'Dalsey, Hillblom and Lynn (DHL)',
  'defence-science-and-technology-agency-dsta': 'Defence Science and Technology Agency (DSTA)',
  'energy-market-authority-ema': 'Energy Market Authority (EMA)',
  'ernst-&-young-ey': 'Ernst & Young (EY)',
  'expressvpn': 'ExpressVPN',
  'f5-networks': 'F5 Networks',
  'foodpanda': 'foodpanda',
  'government-of-singapore-investment-corporation-gic': 'Government of Singapore Investment Corporation (GIC)',
  'globalfoundries': 'GlobalFoundries',
  'govtech': 'GovTech',
  'hol-experiences': 'HOL Experiences',
  'housing-and-development-board-hdb': 'Housing & Development Board (HDB)',
  'hope-technik': 'HOPE Technik',
  'hypotenuse-ai':'Hypotenuse AI',
  'international-business-machines-ibm': 'International Business Machines (IBM)',
  'idemia': 'IDEMIA',
  'integrated-health-information-systems-ihis': 'Integrated Health Information Systems (IHiS)',
  'infocomm-media-development-authority-imda': 'Infocomm Media Development Authority (IMDA)',
  'institute-for-infocomm-research-i2r': 'Institute for Infocomm Research (I2R)',
  'jpmorgan-chase': 'JPMorgan Chase',
  'johnson-&-johnson': 'Johnson & Johnson',
  'kpmg': 'KPMG',
  'mindfi': 'MindFi',
  'monetary-authority-of-singapore-mas': 'Monetary Authority of Singapore (MAS)',
  'ministry-of-education-moe': 'Ministry of Education (MOE)',
  'ministry-of-finance-mof': 'Ministry of Finance (MOF)',
  'national-university-of-sigapore-nus': 'National University of Singapore (NUS)',
  'nextofkin-creatives': 'NextOfKin Creatives',
  'national-computer-systems-ncs': 'National Computer Systems (NCS)',
  'ntuc-income': 'NTUC Income',
  'olivia-lee': 'OLIVIA LEE',
  'oversea-chinese-banking-corp-ocbc': 'Oversea-Chinese Banking Corp (OCBC)',
  'open-government-products-ogp': 'Open Government Products (OGP)',
  'port-of-singapore-authority-psa': 'Port of Singapore Authority (PSA)',
  'paypal': 'PayPal',
  'proctor-&-gamble': 'Procter & Gamble',
  'pricewaterhousecoopers-pwc': 'PricewaterhouseCoopers (PwC)',
  'rbs-design': 'RBS Design',
  'rec-solar': 'REC Solar',
  'st-engineering': 'ST Engineering',
  'stuck-design': 'STUCK Design',
  'singapore-tourism-board-stb': 'Singapore Tourism Board (STB)',
  'singapore-armed-forces-saf': 'Singapore Armed Forces (SAF)',
  'sap': 'SAP',
  'sginnovate-infinity-series': 'SGInnovate Infinity Series',
  'sginnovate-summation-series': 'SGInnovate Summation Series',
  'singapore-institute-of-technology-sit': 'Singapore Institute of Technology (SIT)',
  'sensetime': 'SenseTime',
  'shopback': 'ShopBack',
  'stashaway': 'StashAway',
  'tti-inc': 'TTI, Inc.',
  'tiktok': 'TikTok',
  'trail-of-bits': 'Trail of Bits',
  'ucars': 'UCARS',
}