
export const jobType = [
  { label: 'Full-Time' },
  { label: 'Part-Time' },
  { label: 'Intern' },
  { label: 'Contract' },
  { label: 'Freelance' },
];

export const years = [
  { label: '0' },
  { label: '1' },
  { label: '2' },
  { label: '3' },
  { label: '4' },
  { label: '5' },
  { label: '6' },
  { label: '7' },
  { label: '8' },
  { label: '9' },
  { label: '10' },
  { label: '11' },
  { label: '12' },
  { label: '13' },
  { label: '14' },
  { label: '15' },
  { label: '16' },
  { label: '17' },
  { label: '18' },
  { label: '19' },
  { label: '20' },
  { label: '21' },
  { label: '22' },
  { label: '23' },
  { label: '24' },
  { label: '25' },
  { label: '26' },
  { label: '27' },
  { label: '28' },
  { label: '29' },
  { label: '30' },
];

export const month = [
  { label: 'Jan' },
  { label: 'Feb' },
  { label: 'Mar' },
  { label: 'Apr' },
  { label: 'May' },
  { label: 'Jun' },
  { label: 'Jul' },
  { label: 'Aug' },
  { label: 'Sep' },
  { label: 'Oct' },
  { label: 'Nov' },
  { label: 'Dec' },
];

export const year = [
  { label: '2022' },
  { label: '2021' },
  { label: '2020' },
  { label: '2019' },
  { label: '2018' },
  { label: '2017' },
  { label: '2016' },
  { label: '2015' },
  { label: '2014' },
  { label: '2013' },
  { label: '2012' },
  { label: '2011' },
  { label: '2010' },
];

export const jobCategory = [
    { label: 'Product Manager', category: 'Product' },
    { label: 'Project Manager', category: 'Product' },
    { label: 'Product Operations', category: 'Product' },
    { label: 'Product Designer', category: 'Product' },
    { label: 'UI/UX Designer', category: 'Product' },

    { label: 'QA Engineer', category: 'Software' },
    { label: 'Scrum Master', category: 'Software' },
    { label: 'Software Architect', category: 'Software' },
    { label: 'Software Engineer', category: 'Software' },
    { label: 'Software Manager', category: 'Software' },

    { label: 'AI Engineer', category: 'Data' },
    { label: 'Cyber Security Analyst', category: 'Data' },
    { label: 'Data Analyst', category: 'Data' },
    { label: 'Data Engineer', category: 'Data' },
    { label: 'Data Architect', category: 'Data' },
    { label: 'Data Science', category: 'Data' },
    { label: 'Data Scientist', category: 'Data' },
    { label: 'Database Administrator', category: 'Data' },
    { label: 'Machine Learning Engineer', category: 'Data' },
    { label: 'Statistician', category: 'Data' },
    { label: 'Systems Analyst', category: 'Data' },

    { label: 'Accountant', category: 'Business' },
    { label: 'Administration', category: 'Business' },
    { label: 'Business Analyst', category: 'Business' },
    { label: 'Business Development', category: 'Business' },
    { label: 'Customer Service', category: 'Business' },
    { label: 'Finance', category: 'Business' },
    { label: 'Human Resources', category: 'Business' },
    { label: 'Marketing', category: 'Business' },
    { label: 'Operations', category: 'Business' },
    { label: 'Sales', category: 'Business' },
    { label: 'Dispute Analyst', category: 'Business' },

    { label: 'Business Consultant', category: 'Consulting' },
    { label: 'Consultant', category: 'Consulting' },
    { label: 'Financial Consultant', category: 'Consulting' },
    { label: 'HR Consultant', category: 'Consulting' },
    { label: 'Sales Consultant', category: 'Consulting' },
    { label: 'Technology Consultant', category: 'Consulting' },
    { label: 'Marketing Consultant', category: 'Consulting' },

    { label: 'Aerospace Engineer', category: 'Engineering' },
    { label: 'Biomedical Engineer', category: 'Engineering' },
    { label: 'Chemical Engineer', category: 'Engineering' },
    { label: 'Civil Engineer', category: 'Engineering' },
    { label: 'Computer Engineer', category: 'Engineering' },
    { label: 'Construction Engineer', category: 'Engineering' },
    { label: 'Electrical Engineer', category: 'Engineering' },
    { label: 'Electronic Engineer', category: 'Engineering' },
    { label: 'Environmental Engineer', category: 'Engineering' },
    { label: 'Industrial Engineer', category: 'Engineering' },
    { label: 'Manufacturing Engineer', category: 'Engineering' },
    { label: 'Marine Engineer', category: 'Engineering' },
    { label: 'Materials Engineer', category: 'Engineering' },
    { label: 'Mechanical Engineer', category: 'Engineering' },
    { label: 'Nuclear Engineer', category: 'Engineering' },
    { label: 'Petroleum Engineer', category: 'Engineering' },
    { label: 'Process Engineer', category: 'Engineering' },
    { label: 'Quality Engineer', category: 'Engineering' },
    { label: 'Structural Engineer', category: 'Engineering' },
    { label: 'Systems Engineer', category: 'Engineering' },
    { label: 'Thermal Engineer', category: 'Engineering' },
    
    { label: 'Quant', category: 'Finance' },
    
    { label: 'Researcher', category: 'Research' },

    { label: 'Architect', category: 'Arts & Entertainment' },
    { label: 'Artist', category: 'Arts & Entertainment' },
    { label: 'Athlete', category: 'Arts & Entertainment' },
    { label: 'Comedian', category: 'Arts & Entertainment' },
    { label: 'Culinary Arts', category: 'Arts & Entertainment' },
    { label: 'Curator', category: 'Arts & Entertainment' },
    { label: 'Dance', category: 'Arts & Entertainment' },
    { label: 'Designer', category: 'Arts & Entertainment' },
    { label: 'Entertainer', category: 'Arts & Entertainment' },
    { label: 'Event Planner', category: 'Arts & Entertainment' },
    { label: 'Hairstylist', category: 'Arts & Entertainment' },
    { label: 'Illustrator', category: 'Arts & Entertainment' },
    { label: 'Photographer', category: 'Arts & Entertainment' },
    { label: 'Sculptor', category: 'Arts & Entertainment' },
    { label: 'Singer', category: 'Arts & Entertainment' },
    { label: 'Teacher', category: 'Arts & Entertainment' },
    { label: 'Writer', category: 'Arts & Entertainment' },

  ];

  export const jobLocation = [
    {label: 'Singapore' },
    { label: 'Afghanistan' },
    { label: 'Albania' },
    { label: 'Algeria' },
    { label: 'Andorra' },
    { label: 'Angola' },
    { label: 'Antigua and Barbuda' },
    { label: 'Argentina' },
    { label: 'Armenia' },
    { label: 'Australia' },
    { label: 'Austria' },
    { label: 'Azerbaijan' },
    { label: 'Bahamas' },
    { label: 'Bahrain' },
    { label: 'Bangladesh' },
    { label: 'Barbados' },
    { label: 'Belarus' },
    { label: 'Belgium' },
    { label: 'Belize' },
    { label: 'Benin' },
    { label: 'Bhutan' },
    { label: 'Bolivia' },
    { label: 'Bosnia and Herzegovina' },
    { label: 'Botswana' },
    { label: 'Brazil' },
    { label: 'Brunei' },
    { label: 'Bulgaria' },
    { label: 'Burkina Faso' },
    { label: 'Burundi' },
    { label: 'Côte d\'Ivoire' },
    { label: 'Cabo Verde' },
    { label: 'Cambodia' },
    { label: 'Cameroon' },
    { label: 'Canada' },
    { label: 'Central African Republic' },
    { label: 'Chad' },
    { label: 'Chile' },
    { label: 'China' },
    { label: 'Colombia' },
    { label: 'Comoros' },
    { label: 'Congo (Congo-Brazzaville)' },
    { label: 'Costa Rica' },
    { label: 'Croatia' },
    { label: 'Cuba' },
    { label: 'Cyprus' },
    { label: 'Czechia (Czech Republic)' },
    { label: 'Democratic Republic of the Congo' },
    { label: 'Denmark' },
    { label: 'Djibouti' },
    { label: 'Dominica' },
    { label: 'Dominican Republic' },
    { label: 'Ecuador' },
    { label: 'Egypt' },
    { label: 'El Salvador' },
    { label: 'Equatorial Guinea' },
    { label: 'Eritrea' },
    { label: 'Estonia' },
    { label: 'Eswatini (fmr. "Swaziland")' },
    { label: 'Ethiopia' },
    { label: 'Fiji' },
    { label: 'Finland' },
    { label: 'France' },
    { label: 'Gabon' },
    { label: 'Gambia' },
    { label: 'Georgia' },
    { label: 'Germany' },
    { label: 'Ghana' },
    { label: 'Greece' },
    { label: 'Grenada' },
    { label: 'Guatemala' },
    { label: 'Guinea' },
    { label: 'Guinea-Bissau' },
    { label: 'Guyana' },
    { label: 'Haiti' },
    { label: 'Holy See' },
    { label: 'Honduras' },
    { label: 'Hungary' },
    { label: 'Iceland' },
    { label: 'India' },
    { label: 'Indonesia' },
    { label: 'Iran' },
    { label: 'Iraq' },
    { label: 'Ireland' },
    { label: 'Israel' },
    { label: 'Italy' },
    { label: 'Jamaica' },
    { label: 'Japan' },
    { label: 'Jordan' },
    { label: 'Kazakhstan' },
    { label: 'Kenya' },
    { label: 'Kiribati' },
    { label: 'Kuwait' },
    { label: 'Kyrgyzstan' },
    { label: 'Laos' },
    { label: 'Latvia' },
    { label: 'Lebanon' },
    { label: 'Lesotho' },
    { label: 'Liberia' },
    { label: 'Libya' },
    { label: 'Liechtenstein' },
    { label: 'Lithuania' },
    { label: 'Luxembourg' },
    { label: 'Madagascar' },
    { label: 'Malawi' },
    { label: 'Malaysia' },
    { label: 'Maldives' },
    { label: 'Mali' },
    { label: 'Malta' },
    { label: 'Marshall Islands' },
    { label: 'Mauritania' },
    { label: 'Mauritius' },
    { label: 'Mexico' },
    { label: 'Micronesia' },
    { label: 'Moldova' },
    { label: 'Monaco' },
    { label: 'Mongolia' },
    { label: 'Montenegro' },
    { label: 'Morocco' },
    { label: 'Mozambique' },
    { label: 'Myanmar (formerly Burma)' },
    { label: 'Namibia' },
    { label: 'Nauru' },
    { label: 'Nepal' },
    { label: 'Netherlands' },
    { label: 'New Zealand' },
    { label: 'Nicaragua' },
    { label: 'Niger' },
    { label: 'Nigeria' },
    { label: 'North Korea' },
    { label: 'North Macedonia' },
    { label: 'Norway' },
    { label: 'Oman' },
    { label: 'Pakistan' },
    { label: 'Palau' },
    { label: 'Palestine State' },
    { label: 'Panama' },
    { label: 'Papua New Guinea' },
    { label: 'Paraguay' },
    { label: 'Peru' },
    { label: 'Philippines' },
    { label: 'Poland' },
    { label: 'Portugal' },
    { label: 'Qatar' },
    { label: 'Romania' },
    { label: 'Russia' },
    { label: 'Rwanda' },
    { label: 'Saint Kitts and Nevis' },
    { label: 'Saint Lucia' },
    { label: 'Saint Vincent and the Grenadines' },
    { label: 'Samoa' },
    { label: 'San Marino' },
    { label: 'Sao Tome and Principe	' },
    { label: 'Saudi Arabia' },
    { label: 'Senegal' },
    { label: 'Serbia' },
    { label: 'Seychelles' },
    { label: 'Sierra Leone' },
    // { label: 'Singapore' },
    { label: 'Slovakia' },
    { label: 'Slovenia' },
    { label: 'Solomon Islands' },
    { label: 'Somalia' },
    { label: 'South Africa' },
    { label: 'South Korea' },
    { label: 'South Sudan' },
    { label: 'Spain' },
    { label: 'Sri Lanka' },
    { label: 'Sudan' },
    { label: 'Suriname' },
    { label: 'Sweden' },
    { label: 'Switzerland' },
    { label: 'Syria' },
    { label: 'Tajikistan' },
    { label: 'Tanzania' },
    { label: 'Thailand' },
    { label: 'Timor-Leste' },
    { label: 'Togo' },
    { label: 'Tonga' },
    { label: 'Trinidad and Tobago' },
    { label: 'Tunisia' },
    { label: 'Turkey' },
    { label: 'Turkmenistan' },
    { label: 'Tuvalu' },
    { label: 'Uganda' },
    { label: 'Ukraine' },
    { label: 'United Arab Emirates' },
    { label: 'United Kingdom' },
    { label: 'United States of America' },
    { label: 'Uruguay' },
    { label: 'Uzbekistan' },
    { label: 'Vanuatu' },
    { label: 'Venezuela' },
    { label: 'Vietnam' },
    { label: 'Yemen' },
    { label: 'Zambia' },
    { label: 'Zimbabwe' },
  ];